_main_app/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", include("ui_app.urls"))
]

ui_app/urls.py
from django.urls import path
from .views import home


app_name = "ui_app"

urlpatterns = [path("", home, name="home")]

ui_app/models.py
from django.db import models

# Create your models here.

ui_app/views.py
from django.shortcuts import render
from django.http.response import JsonResponse

from .ai.preprocess import preprocess, predict_digit
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def home(request):
    if request.method == "POST":
        img = preprocess(request.body)
        prdct = predict_digit(img)

        return JsonResponse({"digit": prdct})

    return render(request, "ui_app/home.html", {})

templates/ui_app/home.html
{% extends 'widgets/appbase/appbase.html' %}

{% load static %}

{% block content_block %}

{% csrf_token %}

<link rel="stylesheet" href="{% static 'ui_app/home.css' %}">

<div class="section" id="inpt_section">
    <div class="section_title">
        {% include 'widgets/canvas/canvas.html' %}
    </div>
    <div class="section_content">
        <button id="predict" onclick="predict(this)">Predict</button>
        <button id="clear" onclick="clearCnv();">Clear</button>


        <script>
            const URL = "{% url 'ui_app:home' %}"
        </script>

        <script src="{% static 'scripts/cookies.js' %}"></script>
        <script src="{% static 'scripts/post.js' %}"></script>
        <script src="{% static 'scripts/post_image.js' %}"></script>
        <script src="{% static 'scripts/predict.js' %}"></script>

    </div>
</div>

{% endblock %}

templates/widgets/appbase/appbase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MLZ MNIST</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'widgets/theme_dark.css' %}">

    <link rel="stylesheet" href="{% static 'widgets/button/button.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/section/section.css' %}">


    <link rel="stylesheet" href="{% static 'widgets/appbase/appbase.css' %}">
</head>

<body>

    <div class="section" id="content_section">
        <div class="section_content">
            {% block content_block %}
            {% endblock %}            
        </div>
    </div>
</body>

</html>

templates/widgets/canvas/canvas.html
{% load static %}

<canvas id="img"></canvas>

<script src="{% static 'widgets/canvas/canvas.js' %}"></script>

templates/widgets/footer/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/footer/footer.css' %}">


<div class='footer'>

    <div id="row">
        <div id="logo">
            {% include 'widgets/logo/logo2_0.html' %}
        </div>


        <div class="section">
            <div class="section_content grid2">

                <!--
                <div class="section">
                    <div class="section_title">
                        <h3>Developer info</h3>
                    </div>
                    <div class="section_content">
                        <p>+213 XXX XX XX XX</p>
                        <p>XXXXXXX@gmail.com</p>
                    </div>
                </div>
            -->

                <div class="section">
                    <div class="section_title">
                        <h3>Contact Us</h3>
                    </div>
                    <div class="section_content">
                        <p>+213 XXX XX XX XX</p>
                        <p>+213 XXX XX XX XX</p>
                        <p>instagram.com/XXXXX</p>
                        <p>XXXXXXX@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a id="me" href="https://github.com/zaqks">Designed and Developped By zaqks</a>

    <div id="langs">
        <a style="cursor: pointer;" id="EN">en</a>
        <a style="cursor: pointer;" id="FR">fr</a>
    </div>

    <script src="{% static 'scripts/langs.js' %}"></script>

</div>

templates/widgets/logo/logo2_0.html
{% load static %}


<link rel="stylesheet" href="{% static 'widgets/logo/logo.css' %}">

<div class="logo logo20" onclick="document.location.href=`{% url 'client_app:home' %}`" id="theme_toggle">
  <img src="{% static 'assets/images/logos/svg/logo2.svg' %}" alt="" />
</div>